create table public.entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  captured_at timestamptz not null default now(),
  occurred_at timestamptz,
  category text not null check (category in ('wellbeing', 'reminder', 'habit', 'place', 'social', 'note')),
  status text check (status is null or status in ('planned', 'completed', 'tentative')),
  title text not null,
  original_transcript text not null,
  original_interpretation jsonb not null default '{}'::jsonb,
  confirmed_data jsonb not null default '{}'::jsonb,
  reminder_at timestamptz,
  calendar_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index entries_user_captured_idx on public.entries (user_id, captured_at desc);
alter table public.entries enable row level security;

create policy "Users can read their own entries" on public.entries
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own entries" on public.entries
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own entries" on public.entries
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their own entries" on public.entries
  for delete to authenticated using ((select auth.uid()) = user_id);

create table public.entry_corrections (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.entries(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_name text not null,
  previous_value jsonb,
  corrected_value jsonb,
  created_at timestamptz not null default now()
);

create index entry_corrections_entry_idx on public.entry_corrections (entry_id, created_at);
alter table public.entry_corrections enable row level security;

create policy "Users can read their own corrections" on public.entry_corrections
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own corrections" on public.entry_corrections
  for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger entries_set_updated_at before update on public.entries
for each row execute function public.set_updated_at();
